commodities_dbt:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int}}"
      schema: public
      threads: "{{ env_var('DB_THREADS') | int}}"
      type: postgres
      user: "{{ env_var('DB_USER') }}"
  target: dev