commodities_dbt:
  outputs:
    dev:
      dbname: postgresql_commodities_database
      host: dpg-ctleaspopnds73f9osl0-a.oregon-postgres.render.com
      pass: Q3yqzV3kMPpedBKlOpMi3D4KVjBp8z0C
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgresql_commodities_database_user
  target: dev
